// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBKh_HscY2h3oNgyjx05XQvv0vmw7Ki_k',
    appId: '1:428059422913:web:54e5848bceec945c752440',
    messagingSenderId: '428059422913',
    projectId: 'budget-012',
    authDomain: 'budget-012.firebaseapp.com',
    storageBucket: 'budget-012.appspot.com',
    measurementId: 'G-DSHW9T7PDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fcmPeAO5ofjsZb-FJsN6Qba0tuA11Zk',
    appId: '1:428059422913:android:8ad5f789f86d8c50752440',
    messagingSenderId: '428059422913',
    projectId: 'budget-012',
    storageBucket: 'budget-012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkPhhOFDyOHyKRswowgFSNTUpZO7C3FPo',
    appId: '1:428059422913:ios:b89d977863ffd52e752440',
    messagingSenderId: '428059422913',
    projectId: 'budget-012',
    storageBucket: 'budget-012.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkPhhOFDyOHyKRswowgFSNTUpZO7C3FPo',
    appId: '1:428059422913:ios:8afa04fc743ed654752440',
    messagingSenderId: '428059422913',
    projectId: 'budget-012',
    storageBucket: 'budget-012.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
